authn/verifier_id_token.go
Sync claims from https://github.com/grafana/grafana/blob/651223fe2d69536b3576080a8ea3e6156136bc28/pkg/services/auth/id.go#L23-L28 and update function name to align with `Verifier` and `AccessTokenVerifier`.
=> Fix: sync claims and update function name

authn/config.go, authn/token_exchange.go, authn/token_exchange_test.go
I have been meaning to fix the spelling.
The interface might be nice as callers can implement mocks and pass around the interface instead.
=> ExchangeClient: fix spelling, provide interface

authn/token_exchange.go
Propose to use `TokenExchanger` instead of TokenExchangeClientInterface. This is what we used in [authz-service](https://github.com/grafana/authz-service/blob/main/pkg/authorizer/proxy/proxy.go#L25-L27)
=> Authn: Update interface

README.md, authn/config.go, authn/config_test.go, authn/jwks.go, authn/jwks_test.go, authn/verifier.go, authn/verifier_access_token.go, authn/verifier_id_token.go, authn/verifier_test.go, authz/client.go
It's common to construct `AccessTokenVerifier` and `IDTokenVerifier` together. And they always use the same `SingingKeysURL`. Right now if you construct them both they would use different singing keys logic, i.e. they would separately fetch and cache public jwks.
In this pr I propose to expose and interface `KeyRetriever` and a default implementation that you need to pass when creating a new verifier. This makes is easier to share the logic and underlying store. It is a breaking change but there is not too many places we would need to update
=> Authn: Add interface for KeyRetriever and expose a default implementation

authn/jwks.go
In the scope of the `UniStore` work, given `Grafana` is relying on a self signed https certificate for local testing, I'd like to be able to replace the client with one that has `tls.Config{InsecureSkipVerify: true}`
=> Authn: Allow configuring the key retriever http client

authn/caller_info.go, authz/multitenant_client.go, authz/multitenant_client_test.go, go.mod, go.sum
This PR adds the first elements of the new multi-tenant AuthZ client.
Mostly we introduce a new caller concept, which is the bundle of an access token and id token, that we will use to authorize requests:
```mermaid
classDiagram
class CallerAuthInfo{
+IdClaims
+AccessClaims
}
```
Then we implement the following flow, wrapping the Read endpoint of the Authorization Service (proxy) and enforcing access control:
```mermaid
flowchart TD
A[Check<br>Caller, StackID<br>Action, Resource, CtxResource ] --> B{if Caller is Service}
B -->|yes| C{if Caller.AccessClaims<br>has action in permission}
C -->|yes| YES[YES]
C -->|no| NO[NO]
B -->|no| F{if Caller.AccessClaims<br>has action in delegatedPermission}
F -->|no| NO1[NO]
F -->|yes| G[read user permissions<br>Caller.IdClaims.NamespaceID, StackID, …
```
=> AuthZ: Add multi-tenant client

authn/errors.go, authn/grpc_client_interceptors.go, authn/grpc_client_interceptors_test.go
This PR adds a new grpc client interceptor that adds access tokens to the outgoing context of grpc calls.
Open question for later:
- how to handle missing ID tokens? Given for service communications it might be normal not to have a user involved. But there might be cases where the service wants to make requests on behalf of a user and in such cases a missing user might be an error.
=> AuthN: gRPC Client Interceptor

authn/grpc_client_interceptors.go, authn/grpc_client_interceptors_test.go
This PR allows users to add id tokens to the grpc metadata in the outgoing context.
Additionally, to cover future usage, this PR allows adding additional decorators to the metadata.
=> AuthN: Add id token to gRPC client interceptors

authn/namespace.go, authz/multitenant_client.go, authz/multitenant_client_test.go
**PR changes:**
- Introduces a configurable namespace formatter, with implementations for onprem (org based namespaces) and cloud (stack based namespaces)
- Adds the namespace validation logic to the AuthZ client. 
**Benefits:**
- **Flexibility:** The authorization client can now easily adapt to different environments with varying namespace formats.
- **Security:**  Access control checks in other namespaces will result in forbidden access.
**Testing:**
- Unit tests have been updated to cover the new namespace formatters.
=> AuthZ: Add namespace validation

authz/multitenant_client.go, authz/multitenant_client_test.go
This PR adds an unsafe option to make access tokens options.
This is meant to be used on-prem while access tokens are not possible to use there.
=> AuthZ: LegacyClient - Add option to make access tokens optional

authn/grpc_client_interceptors.go, authn/grpc_client_interceptors_test.go
This PR adds an unsafe option to make access tokens options.
This is meant to be used on-prem while access tokens are not possible to use there.
=> AuthN: gRPC Client Interceptors - Add option to make access tokens optional

authz/multitenant_client.go
I had forgotten the use case where we'd want to run the client with in-proc gRPC.
With this additional option, we can:
```go
channel := &inprocgrpc.Channel{}
channel.RegisterService(
grpchan.InterceptServer(
&authzv1.AuthzService_ServiceDesc,
srvOpts...,
),
server,
)
conn := grpchan.InterceptClientConn(channel, clientOpts...)
client, err := NewLegacyClient(
&MultiTenantClientConfig{},
WithGrpcConnectionLCOption(conn),
)
```
=> AuthZ: LegacyClient - Option to override the gRPC connection

authn/caller_info.go, authn/grpc_authenticator.go, authn/grpc_authenticator_test.go, authn/grpc_client_interceptors.go
This PR introduces a new gRPC authenticator that verifies incoming requests based on access and ID tokens.
**Key changes:**
* Adds `GrpcAuthenticator` that performs authentication based on access and ID tokens present in the request metadata.
* Verifies the tokens using existing `Verifier` implementations for both access and ID tokens.
* Extracts the stack ID from the request metadata and ensures both tokens belong to the expected namespace.
* Validates the token subject types, allowing only specific types for access and ID tokens.
* Returns a context enriched with caller information upon successful authentication.
**TODOs:**
* Implement constructor for `GrpcAuthenticator`.
* Make ID token verification optional.
* Allow configuration of metadata keys for tokens and stack ID.
* Implement …
=> AuthN: Add gRPC authenticator

authn/grpc_authenticator.go, authn/grpc_authenticator_test.go
This PR makes the gRPC authenticator configurable.
It adds a constructor to the gRPC Authenticator with configuration and options.
One of the option is to make id tokens optional or required.
=> AuthN: Make gRPC authenticator configurable

authn/grpc_authenticator.go, authn/grpc_authenticator_test.go
This PR adds an unsafe option to make access tokens optionals.
This is meant to be used on-prem while access tokens are not possible to use there.
=> AuthN: gRPC authenticator option to disable access tokens

authn/grpc_authenticator.go, authn/grpc_authenticator_test.go, authn/grpc_client_interceptors.go, authn/grpc_client_interceptors_test.go, authz/multitenant_client.go, authz/multitenant_client_test.go
This PR is mainly clean ups.
- Inline `grpcAuthenticator`, `grpcClientInterceptor` & `legacyClient's` way to disable access tokens (using an option rather than a config field)
- Remove unnecessary returned error from `LegacyClientOption`.
=> AuthNZ: Revert logic on access token disabling option

authn/verifier_id_token.go
Related to https://github.com/grafana/grafana/pull/90992
Adds `DisplayName` as a field called `name` to the ID Token claims.
=> Authn: Add DisplayName to ID Token Claims

authn/caller_info.go, authn/grpc_authenticator.go, authn/grpc_authenticator_test.go, authn/grpc_client_interceptors.go, authz/namespace.go, authz/namespace_test.go
**Aka: three step authnz (authentication, namespace access control, permission access control)**
In #60 I tried to assess if I could extract the stackID required for the namespace check from different sources. It turns out it's complicated in the gRPC Stream case.
It made me question whether performing namespace validation in the authentication interceptor was the correct thing after all.
- Authentication: Verifying the identity of the caller. In our case, this is handled by validating the JWT tokens against the signing authority. We've already confirmed **who** is making the request.
- Authorization: Determining if the authenticated caller has the necessary permissions to access a specific resource or perform a specific action. This is where the **namespace validation** and **rbac …
=> AuthNZ: Extract namespace validation from gRPC authentication 

authn/claims.go, authn/verifier_id_token.go, claims/token.go, claims/type.go
After inspecting what we get in our claims we need to adjust the methods a bit, specifically UID is sent with a prefix.
I will also make a pr in grafana to add the identity type to all issued tokens.
We also probably won't need InternalID and OrgID for now so lets remove them
Edit:
After talk with Ryan we have adjusted the interface and id claims a bit. Nothing should be relying on these types yet so we should be fine to break them
=> Adjust ID Token claims

authn/claims.go, authn/grpc_authenticator_test.go, authn/token_exchange_test.go, authn/verifier_access_token.go, authn/verifier_id_token.go, authz/multitenant_client_test.go, authz/namespace.go, authz/namespace_test.go, claims/namespace.go, claims/namespace_test.go
There has been some miscommunication within our working group and it made its way into OSS code and into auth/authlib, which is that cloud namespace format is `stack-<stackID>`.
This is incorrect. Cloud namespaces are `stacks-<stackId>` historically.
[Slack convo](https://raintank-corp.slack.com/archives/C037H5GAY9L/p1724257160817399?thread_ts=1722433605.876979&cid=C037H5GAY9L).
This change-set tries to take care of the problem in a backwards-compatible way. In talking with @kalleep, we decided to treat both `stack-<stackId>` and `stacks-<stackId>` as valid for the time being.
While I was at it, I was very happy to see that something like NamespaceAccessChecker exists. I would love to use it for some use-cases but its reliance on me knowing `stackID` was something discouraging due to the …
=> NamespaceMapper: conform to cloud pluralized stacks-<id> namespace

authn/claims.go, authn/grpc_authenticator.go, authn/verifier_access_token.go, authn/verifier_id_token.go, authz/multitenant_client.go, authz/namespace.go, claims/namespace.go, claims/token.go
In collaboration with @ryantxu.
=> Move the namespace matches outside of access/id implementations

claims/namespace.go, claims/namespace_test.go
When returning errors from `ParseNamespace`, we ran into broken auth when reaching `/apis` on an instance of Grafana.
This fixes it.
=> fix: resolves issues with broken discovery in Grafana

authn/grpc_authenticator.go, authn/grpc_client_interceptors.go, authz/namespace.go, authz/namespace_test.go
This PR enhances the namespace checker with tracing capabilities.
**Key changes:**
* Introduces tracing to the namespace checker.
* A noop tracer is used by default, ensuring no performance overhead when tracing is disabled.
* Provides the option to configure a custom tracer.
* Modifies the signature of CheckAccess to accept a context object, enabling trace propagation.
=> Add Tracing to Namespace Checker

authz/client.go
The PR passes the HTTP client of `authz` to the `KeyRetriever`. This ensures any options passed to `authz` client will be passed to `KeyRetriever`. A common use case is to skip TLS checks in development environment where this option must be passed to `KeyRetriever` as well to ignore certificate errors while fetching signing keys.
=> Pass authz's http client to verifier

authz/client.go, authz/client_test.go
This pull request introduces enhancements to the authorization checks, specifically by adding support for more granular actions. E.g. `dashboard.grafana.app/dashboards/dashUID:get`.
=> AuthZ: Add support for Granular Actions

authz/client.go, authz/client_test.go
Given the team that needed granular token permissions needs something more flexible. We'll remove that feature until another request is made.
=> AuthZ: Remove support for granular token permission

authn/grpc_client_interceptors.go, authn/grpc_client_interceptors_test.go
This updates the outgoing GRPC context so it keeps any existing headers.
Required for: https://github.com/grafana/grafana/pull/99199 -- where we try to send request headers in the connection.
=> GRPC: Keep existing outgoing headers

authz/client.go
We should use `types.NamespaceMatches` to verify namespace
=> Authz: Use NamespaceMatches to verify namespace in checker

authn/verifier_id_token.go
We have had a need come up in addressing a need in the new Direct API Server access project in app platform, which requires being able to determine user's access in cloud auth webhook with a single Authorization header.
The issue is that the authz-service currently is not capable for helping cloud webhook determine what the user's org role is. Until that is the case, we would like to package that within the id token and use our own proprietary format to string together the tokens in the Authorization header.
=> feat: add org role claim to id token

authz/client.go, authz/client_test.go
With https://github.com/grafana/grafana/pull/99573, we now systematically have access token claims.
This PR removes the possibility to disable access tokens thus making the client safer to use since it's not possible anymore to get authorized without a real identity.
Note: wait for https://github.com/grafana/grafana/pull/99573 to be merged
Fixes https://github.com/grafana/identity-access-team/issues/1129
=> Authz: Remove disable access token option

authz/client.go, authz/client_test.go
This PR simplifies the AuthZ Client code.
We don't handle setting up the gRPC connection in the lib anymore.
=> AuthZ: Change constructor to receive a connection

types/type.go
See https://github.com/grafana/grafana/pull/100336#pullrequestreview-2605504736
Support a "public" identity so we clearly say that no authentication has happened
=> Add public identity type

authn/authenticator.go, authn/authenticator_test.go, authn/const.go, authn/grpc_client_interceptors.go, authn/grpc_client_interceptors_test.go, authn/token_exchange.go
I looked through the usage of client interceptor within grafana.
We no longer use `WithDisableAccessTokenOption` so that was removed. We also never use any of these options:
* `WithMetadataExtractorOption`
* `AccessTokenMetadataKey`
* `IDTokenMetadataKey`
So to clean this component up a bit I changed it so that this one accepts a `TokenExchanger` and move everything else to options. 
Additional changes
* Rename all options to have matching prefix `WithClientInterceptor`
* Added `StaticTokenExchanger` that we can use instead of https://github.com/grafana/grafana/blob/b850c9fa68930bd94d93caae524f2e3dabf79218/pkg/services/authn/grpcutils/inproc_exchanger.go#L14C6-L14C21.
* Removed `IDTokenAuthenticator`, we did not end up using this one
=> Chore: cleanup authenticator and client interceptor

authz/client.go, authz/client_test.go
We always map verb `list` to `get` for authorization. But here we do required it for access tokens. So if you want to list using access token you also need `group/resource:list`. We should re-map it for them too
=> Authz: We don't use "list" for authz so we should not require it for access tokens

authz/client.go
This PR fixes the split count in `hastPermissionInToken` since we expect at max 2 parts.
This currently has no incidence given the explicit switch case statement was already filtering out `>3` parts results.
=> AuthZ: Fix split count in `hasPermissionInToken`

authz/client.go
Zanzana is using user UIDs to perform access control checks.
The AuthZ service is able to work with both IDs and UIDs.
This PR proposes a switch to UIDs.
We have to check for other identity kinds that everything remains operational. (Anonymous, Rendering)
=> AuthZ: Switch to uids

authn/token_exchange.go, authn/token_exchange_test.go
Part of https://github.com/grafana/identity-access-team/issues/1217.
Relates to https://github.com/grafana/auth/pull/854.
---
This PR introduces support for specifying a custom expiration when exchanging tokens. If not provided, the default will be 10 minutes. 
As a side note, if the signing access policy token defines a `maxExpiration` attribute, a 400-level error will be returned by the API.
=> identity: Add support for custom expiration when exchanging tokens

authn/auth_info.go, authn/const.go
Return the `AccessTokenClaims.Rest.ServiceIdentity` in `AuthInfo.GetExtra()` if the service identity is specified/not empty.
=> Return serviceIdentity in the AuthInfo.GetExtra if it's not empty

authn/auth_info.go
This pull request includes a small refactor to the `GetExtra` method in `authn/auth_info.go`. 
The change populates the service identity in the extra map, even if an id token is involved in the query.
This allows services to check which service is making a call when receiving on-behalf-of user requests.
=> AuthN: Maintain service identity during obo requests

authn/auth_info.go, authn/auth_info_test.go, authn/authenticator.go, authz/client.go, authz/client_test.go, types/access.go, types/namespace_test.go
Based on these github comments: https://github.com/grafana/auth/pull/884#discussion_r2138168188.
We deliberately do not set the namespace in the identity actor when exchanging tokens through the access token OBO flow. This PR ensures that the root-level namespace is used instead.
=> Expect no namespace in ID token claims for access token OBO flow

authn/verifier_access_token.go, authn/verifier_access_token_test.go
Part of https://github.com/grafana/identity-access-team/issues/1490.
See https://github.com/grafana/identity-access-team/issues/1490#issuecomment-3045355275 for more context.
---
This PR adds a new helper function, `AccessTokenClaims.OnBehalfOfUser`, which lets us easily tell if an access token is being used for a user (and, by extension, if it’s on behalf of a machine).
=> identity: Add helper method for determining if at is on-behalf-of-user
