authn/verifier_access_token.go, authn/verifier_id_token.go
Add namespace to id token claims.
Part of https://github.com/grafana/identity-access-team/issues/659
=> AuthN: Add namespace to id token claims

authn/jwks.go, authn/jwks_test.go, authn/verifier_test.go, authz/client.go
=> Authn: Fix spelling

authn/jwks_test.go, authn/verifier_id_token.go, authn/verifier_test.go
Related to https://github.com/grafana/identity-access-team/issues/770
Related to https://github.com/grafana/grafana/pull/90240
=> Authn: Add Username and UID claim to IDTokenClaims

authz/multitenant_client.go, authz/multitenant_client_test.go
Add caching to the Legacy Client Impl
=> MultiTenantClient: Add caching

authz/multitenant_client.go
For improved debuggability, we've enhanced tracing capabilities. We realized logging wasn't the best fit for a library.
=> AuthZ: Improve tracing for debugging

go.mod, go.sum
=> chore: bump claims package to latest

authn/claims.go, authn/config.go, authn/grpc_authenticator.go
- skip audience checks for ID tokens
- fix nil check in `AuthInfo.GetExtra()`
- add missing yaml tags to `TokenExchangeConfig`
=> [authn] skip audience checks for ID tokens & other fixes

authn/grpc_authenticator.go, authn/grpc_authenticator_test.go
Follow-up to https://github.com/grafana/authlib/pull/81
This PR adds `NewUnsafeGrpcAuthenticator` constructor, which uses of the `NewUnsafeIDTokenVerifier` and `NewUnsafeAccessTokenVerifier`.
This is meant to be used in Unified Storage for in-process mode.
=> [authn] add `NewUnsafeGrpcAuthenticator`

authn/grpc_authenticator.go, authn/grpc_authenticator_test.go, authn/grpc_client_interceptors.go
This PR adds tracing to the `authn` gRPC interceptors.
=> [authn] add tracing to gRPC interceptors

authz/namespace.go, authz/namespace_test.go
This PR updates the `NamespaceAuthorizationFunc` to use the `namespace` to check service access, instead of the `stackID`. 
Currently, authorization relies on extracting the `stackID` from gRPC metadata. However, using the `namespace` (e.g., `stacks-13`) directly provides several advantages:
- Distinguishing between `org-id` and `stacks-id` can be confusing for users. Namespaces abstract away this internal complexity.
- Working directly with namespaces improves code readability.
- If the namespace format changes users won't be impacted.
=> Authz: Refactor `NamespaceAuthorizationFunc` to work with `Namespace`

authz/multitenant_client_test.go
Enhances test coverage for the multi-tenant client, specifically focusing on access control checks for user permissions on resource types (e.g., can a user access all dashboards?).
=> Multi-Tenant Client: Add more tests for wildcards

authn/grpc_authenticator.go, authn/grpc_authenticator_test.go, authn/unsafe_verifier_test.go, authn/verifier_test.go, claims/type.go
When looking at another pr I noticed that we had some duplicated code with a comment to remove when we move it over from grafana core. That has been done so I cleaned it up
=> Chore: Replace duplicated code

authz/client.go
Merged https://github.com/grafana/authlib/pull/109 without accounting for @eleijonmarck comment, my apologies :pray:
=> AuthZ: Increase cleanup interval on Client cache

authn/grpc_authenticator.go, authn/grpc_authenticator_test.go
Fix issue when a request contains a id token for anything other than user or service account
=> Authn: Fix validation check for id tokens

authz/client.go, go.mod, go.sum
=> Authz: No longer return error from client

authn/authenticator.go, authn/errors.go, authn/token_exchange.go
Wrap errors and expose `IsUnauthorizedErr`
=> Authn: errors

authz/client.go, types/access.go
Ensure we validate the request consistently across implementations of Check/Compile.
Context [thread](https://raintank-corp.slack.com/archives/C06JFJ7H3GC/p1739975483455959)
=> validate Check/Compile requests

authn/verifier_access_token.go
Add Actor ("act") claim to AccessTokenClaims.
=> Add Actor to AccessTokenClaims

authn/token_exchange.go, authn/token_exchange_test.go
Add access token propagation/access token exchange to the lib.
=> Add SubjectToken for token propagation/access token exchange

authn/auth_info.go, authn/auth_info_test.go, authn/verifier.go, authn/verifier_access_token.go, authn/verifier_access_token_test.go, authz/client.go, authz/client_test.go
Part of https://docs.google.com/document/d/1jPsKAsobIXPnVZgllNZGfIMqFA8kwVGfq92H6pmrDoY/edit?tab=t.0.
@mgyongyosi I'm definitely a bit naive on some of this stuff, but I figured I'd get a PR up so we could work async a bit more easily. Wdyt?
I've started the Auth API work as well, but since it depends on this I figured I'd start here.
=> Allow user as actor in access token

authn/auth_info.go
Based on [this comment](https://github.com/grafana/authlib/pull/173#discussion_r2140026373).
=> Do not implicitly disguise access token as ID token
